name: Checks

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - run: pip install -r requirements.txt
      - run: python3 -m unittest discover -s tests -p "test_*.py"

      - run: npm ci
      - run: npm run check
